f1 = open("01", mode="r")
f2 = open("02_text", mode="w")
f3 = open("03", mode="w+")
print("f1 : ")
print("Readable? " , f1.readable())
print("Writeable? " , f1.writable())
print("f2 : ")
print("Readable? " , f2.readable())
print("Writeable? " , f2.writable())
print("f3 : ")
print("Readable? " , f3.readable())
print("Writeable? " , f3.writable())