a = (123 , "abc" , "  " , 90.99 , False , 123)
b = a*2
print(b)
print(len(a))
print(a.count(123))
print(a.index("abc"))
print()
print("Other tuple : ")
tp = (1,6,4,2,0)
print(tp)
print("Min in tuple : " , min(tp))
print("Max in tuple : " , max(tp))
print("Sorted tuple : " , sorted(tp))
print("Sum of elements of tuple : " , sum(tp))
