tp = (1,2,3,4)
print("Tuples are immutable")
print(tp)
tp = list(tp)
print("Lists are mutable")
print(tp)
tp.append(990)
print("Element added to list.")
print(tp)
tp = tuple(tp)
print("List converted to tuple")
print(tp)
