weight = float(input("Enter your weight in kgs : "))
height = float(input("Enter your height in metres : "))
BMI = weight / (height*height)
if BMI<18.5 : print("Underweight")
elif BMI>18.5 and BMI<=24.9 : print("Normal")
elif BMI>24.9 and BMI<=29.9 : print("Overweight")
else : print("Obese")